spring:
  data:
    mongodb:
      uri:  mongodb+srv://AlpishJain:dFWwFXGr2n3u6dq1@cluster0.ie8sm.mongodb.net/journal_entries?retryWrites=true&w=majority
      database: journaldb
      auto-index-creation: true

server:
  port: 8081
  servlet:
    context-path: /journal
